apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJhWE5oZG1Fek5qRTZaMmh3WDBWWE5IaFdXbUp4TlVWME1rTjRRMlppY0d4MGFHazNVR05GUlRaUlZ6RndiVlphVlE9PSIKCQl9Cgl9Cn0K
type: kubernetes.io/dockerconfigjson
