apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJhWE5oZG1Fek5qRTZaMmh3WDBWR05VbE9RMmhzTkZKWE4xazVRVzl6UkhGeVpsZElWakJTUVVwWFF6STRWbkpLWlE9PSIKCQl9Cgl9Cn0K
type: kubernetes.io/dockerconfigjson
